[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Path that installers should place binaries in
install-path = "~/.rust-mcp-stack/bin"
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Whether to install an updater program
install-updater = false
# Whether dist should create a Github Release or use an existing draft
create-release = false
# A GitHub repo to push Homebrew formulas to
tap = "rust-mcp-stack/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]


[dist.github-custom-runners]
runner = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-22.04"

# [package]
# homepage = "https://rust-mcp-stack.github.io/rust-mcp-filesystem"
